In [ ]:
# -*- conding: utf-8 -*-

In [ ]:
"""
https://deepage.net/features/numpy-numpy.html
あなたのデータサイエンス力を飛躍的に向上させるNumPy徹底入門
1.1　NumPyの基本とインストール方法
1.1.2 10分で学ぶNumPy速習チュートリアル
"""

In [ ]:
"""
np.array([])
np.arange(x, y, z) #(x~yまでをz間隔で) 
np.linspace(x, y, z) #(x~yまでをz等分)
np.array([[]]) #二次元配列
配列.shape #配列の形状
np.sum() #総和　axis→行列指定
配列.reshape(x, y) #配列の形状を変える
配列.T #転値を行う
np.transpose(配列)　#転値を行う
np.random.randn() #正規分布に従った値を返す
np.random.rand() #0-1までの値の中で乱数を返す
np.random.randn(2,3) #()の中で配列の形状を指定
配列[::-1] #とりあえずひっくり返したいとき
"""

In [ ]:
#1.1.2 10分で学ぶNumPy速習チュートリアル

In [1]:
import numpy as np

In [2]:
# 簡単な配列をつくる
a = np.array([1,2,3])

In [3]:
# 配列同士で足し算や掛け算をする
a * 3

array([3, 6, 9])

In [4]:
a + 2

array([3, 4, 5])

In [5]:
b = np.array([2,2,0])

In [6]:
#配列同士で演算をする
a + b 

array([3, 4, 3])

In [7]:
a / b

C:\Users\ayana\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([0.5, 1. , inf])

In [8]:
a * b #配列同士の積をアダマール積という

array([2, 4, 0])

In [9]:
#内積をする
np.dot(a,b)

6

In [11]:
#決まった数までに連続した値をつくる
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
#0-10までを2ごとに区切る
np.arange(0, 10, 2) #(始点, 終点, 間隔)


array([0, 2, 4, 6, 8])

In [16]:
#決まった区間を15等分する
np.linspace(0, 10, 15) #0-10までを15等分

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

In [18]:
#2次元配列
c = np.array([[1, 2, 3], [4, 5, 6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
c.shape

(2, 3)

In [20]:
#3次元配列
d = np.array([[[1,2,3], [4,5,6], [7,8,9], [10,11,12]], 
              [[13,14,15], [16, 17, 18], [19,20,21],[22,23,24]]])

In [21]:
d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [23]:
d.shape

(2, 4, 3)

In [ ]:
#4*3行列が2つ並んでる

In [24]:
#和を求める
np.sum(c)

21

In [25]:
#各列ごとの和を求める
np.sum(c, axis=1)

array([ 6, 15])

In [26]:
np.sum(c, axis=0)

array([5, 7, 9])

In [28]:
np.sum(d, axis=2)

array([[ 6, 15, 24, 33],
       [42, 51, 60, 69]])

In [29]:
np.sum(d, axis=0)

array([[14, 16, 18],
       [20, 22, 24],
       [26, 28, 30],
       [32, 34, 36]])

In [30]:
#配列の形状を変える
c.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [31]:
c.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [32]:
#転置を行う
c.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [34]:
np.transpose(c)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [35]:
#乱数発生
np.random.randn() #正規分布にしたがった値を返す

0.5280937387459554

In [36]:
np.random.rand() #0-1までの値の中で乱数を返す

0.8316960478493348

In [37]:
#()の中で配列の形状を指定
np.random.randn(2,3)

array([[ 0.99406289, -0.12044683, -0.8887099 ],
       [-1.62832051,  1.35166819, -2.61053985]])

In [38]:
#インデックスとスライシング
a[0]

1

In [39]:
a[2]

3

In [40]:
a[1] = 3
a

array([1, 3, 3])

In [41]:
a[1] = 2
a

array([1, 2, 3])

In [42]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
c[0, 0]

1

In [44]:
c[0, 2]

3

In [45]:
c[1, 2]

6

In [46]:
#スライシング
d = np.array([0, 5, 2, 7, 1, 9])
d[1:5]

array([5, 2, 7, 1])

In [47]:
d[1:3]

array([5, 2])

In [48]:
d[0:5:2] #始点：終点：間隔

array([0, 2, 1])

In [49]:
d[::-1] #とりあえずひっくり返したいとき

array([9, 1, 7, 2, 5, 0])

In [50]:
# ブロードキャスティング
#　配列の形状に合わせて適宜配列を拡張してくれる
a

array([1, 2, 3])

In [51]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
a + c

array([[2, 4, 6],
       [5, 7, 9]])

In [53]:
a * c

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [60]:
#高速演算
import numpy as np
import time
def calculate_time():
    a = np.random.randn(100000)
    b = [a]
    start_time = time.time()
    for _ in range(1000):
        sum_1 = np.sum(a)
    print("Using Numpy\t %f sec" % (time.time() - start_time))
    start_time = time.time()
    for _ in range(1000):
        sum_2 = sum(b)
    print("Not using Numpy\t %f sec" % (time.time() - start_time))

calculate_time()

Using Numpy	 0.181292 sec
Not using Numpy	 0.096642 sec


In [ ]:
# numpyのほうがおっせい！！

In [61]:
# IPythonのtimeitを使って計測 
import numpy as np
a = np.random.randn(10000000)
%timeit np.sum(a)

22.8 ms ± 1.07 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [62]:
%timeit sum(a)

3.35 s ± 158 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
